### ISSUE TITLE
wrong placement of tone mark in some syllables with three vowels

### ISSUE THREAD

**Issue by KIRINPUTRA** [OMAMA-Taioan/khiin-rs#18]
例 1

TARGET OUTPUT
khoài

INPUT
khoaif

CURRENT OUTPUT
khòai

This problem should be easy to fix, but the Javascript applet has the correct behavior. I am curious why we have the wrong behavior here, b/c there could be other similar problems that we haven't discovered yet; has the code been modified versus the Javascript applet?

例 2

TARGET OUTPUT
soāiⁿ-á

INPUT
sojainndas

CURRENT OUTPUT
sóai-aⁿ

**Comment by Xarvis** [comment]
https://github.com/OMAMA-Taioan/khiin-rs/pull/21
