### ISSUE TITLE
(MAC) Buffer (display) doesn't update after backspace if (len == 1)

### ISSUE THREAD

**Issue by KIRINPUTRA** [OMAMA-Taioan/khiin-rs#20]
例 1

input = G«BACKSPACE»

expected output == «NOTHING»

current output == 其實是 «NOTHING»; 看起來是 "G"

例 2

input = .G«BACKSPACE»«BACKSPACE»

expected output == «NOTHING»

current output == .

**Comment by Xarvis** [comment]
https://github.com/OMAMA-Taioan/khiin-rs/pull/21
